// Mocks generated by Mockito 5.4.4 from annotations
// in online_exam_c1_online/test/presentation/login/LoginViewModel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:online_exam_c1_online/domain/common/ApiResult.dart' as _i5;
import 'package:online_exam_c1_online/domain/model/User.dart' as _i6;
import 'package:online_exam_c1_online/domain/repository/AuthRepository.dart'
    as _i2;
import 'package:online_exam_c1_online/domain/usecase/LoginUsecase.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i3.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i2.AuthRepository);

  @override
  set authRepository(_i2.AuthRepository? _authRepository) => super.noSuchMethod(
        Invocation.setter(
          #authRepository,
          _authRepository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.Result<_i6.User?>> invoke(
    String? email,
    dynamic password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i5.Result<_i6.User?>>.value(
            _i7.dummyValue<_i5.Result<_i6.User?>>(
          this,
          Invocation.method(
            #invoke,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i5.Result<_i6.User?>>);
}
