// Mocks generated by Mockito 5.4.4 from annotations
// in online_exam_c1_online/test/domain/usecase/LoginUseCase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:online_exam_c1_online/domain/common/ApiResult.dart' as _i4;
import 'package:online_exam_c1_online/domain/model/User.dart' as _i5;
import 'package:online_exam_c1_online/domain/repository/AuthRepository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.User?>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
            _i6.dummyValue<_i4.Result<_i5.User?>>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User?>>);

  @override
  _i3.Future<_i4.Result<_i5.User?>> register(
    String? username,
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? rePassword,
    String? phone,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            username,
            firstName,
            lastName,
            email,
            password,
            rePassword,
            phone,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
            _i6.dummyValue<_i4.Result<_i5.User?>>(
          this,
          Invocation.method(
            #register,
            [
              username,
              firstName,
              lastName,
              email,
              password,
              rePassword,
              phone,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User?>>);
}
